"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { apiFetch, formatINR, type Booking } from "../../lib/api";
import { Button } from "../ui/Button";
import { Badge, Card } from "../ui/Surface";
import { EmptyState, Notice } from "../ui/Feedback";

function tone(state: string) { return state === "CANCELLED" ? "danger" : state === "PENDING_PAYMENT" ? "warning" : "success"; }
export function BookingList() { const [bookings, setBookings] = useState<Booking[]>([]); const [error, setError] = useState(""); useEffect(() => { apiFetch<Booking[]>("/bookings").then(setBookings).catch((cause: Error) => setError(cause.message)); }, []); if (error) return <Notice tone="error">{error}</Notice>; if (!bookings.length) return <Card><EmptyState title="No bookings yet">Your upcoming support requests will appear here once you arrange a service.</EmptyState><div className="center-action"><Link href="/customer/services"><Button>Explore services</Button></Link></div></Card>; return <div className="booking-list">{bookings.map((booking) => <Link href={`/customer/bookings/${booking.id}`} key={booking.id}><Card className="booking-row"><div><p className="eyebrow">{booking.reference}</p><h2>{booking.serviceName}</h2><p className="muted">{new Date(booking.scheduledStart).toLocaleString("en-IN")} · {booking.durationMinutes / 60} hours</p></div><div className="booking-row-end"><Badge tone={tone(booking.state) as "danger" | "warning" | "success"}>{booking.state === "PENDING_PAYMENT" ? "Awaiting confirmation" : booking.state}</Badge><strong>{formatINR(booking.estimateAmountMinor)}</strong></div></Card></Link>)}</div>; }

export function BookingDetail({ id }: { id: string }) { const [booking, setBooking] = useState<Booking | null>(null); const [error, setError] = useState(""); const [cancelling, setCancelling] = useState(false); useEffect(() => { apiFetch<Booking>(`/bookings/${id}`).then(setBooking).catch((cause: Error) => setError(cause.message)); }, [id]); const cancel = async () => { setCancelling(true); try { setBooking(await apiFetch<Booking>(`/bookings/${id}/cancel`, { method: "POST" })); } catch (cause) { setError((cause as Error).message); } finally { setCancelling(false); } }; if (error) return <Notice tone="error">{error}</Notice>; if (!booking) return <Card><p className="muted">Loading booking…</p></Card>; return <><div className="page-heading"><div><p className="eyebrow">Booking {booking.reference}</p><h1>{booking.serviceName}</h1><p className="muted">Provider assignment will happen after confirmation.</p></div><Badge tone={tone(booking.state) as "danger" | "warning" | "success"}>{booking.state === "PENDING_PAYMENT" ? "Awaiting confirmation" : booking.state}</Badge></div><div className="detail-columns"><Card eyebrow="Your request" title="At a glance"><div className="review-list"><div><span>When</span><strong>{new Date(booking.scheduledStart).toLocaleString("en-IN")}</strong></div><div><span>Duration</span><strong>{booking.durationMinutes / 60} hours</strong></div><div><span>Estimated total</span><strong>{formatINR(booking.estimateAmountMinor)}</strong></div><div><span>Payment</span><strong>Not collected yet</strong></div></div></Card><Card eyebrow="Timeline" title="What happens next"><div className="timeline">{booking.events.map((event) => <div className="timeline-item" key={event.id}><span className="timeline-dot" /><div><strong>{event.type === "BOOKING_CREATED" ? "Request created" : event.type === "BOOKING_CANCELLED" ? "Booking cancelled" : "Booking updated"}</strong><p>{event.note}</p><small>{new Date(event.createdAt).toLocaleString("en-IN")}</small></div></div>)}</div></Card><Card eyebrow="Your instructions" title="Requirements"><p className="card-copy">{booking.requirements || "No additional instructions were added."}</p></Card><Card eyebrow="Actions" title="Need to change plans?"><p className="card-copy">Cancellation is available before payment and before confirmation. No refund is applicable because payment has not been collected.</p>{booking.state === "PENDING_PAYMENT" && <Button variant="danger" onClick={cancel} disabled={cancelling}>{cancelling ? "Cancelling…" : "Cancel booking"}</Button>}</Card></div></>; }
