"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { apiFetch, formatINR, type Address, type Booking, type FamilyMember, type Service } from "../../lib/api";
import { Button } from "../ui/Button";
import { Card } from "../ui/Surface";
import { EmptyState, Notice } from "../ui/Feedback";
import { Field } from "../ui/Field";

const steps = ["Who", "Service", "Place", "When", "Details", "Review"];

export function BookingWizard({ initialService }: { initialService?: string | undefined }) {
  const [step, setStep] = useState(0);
  const [services, setServices] = useState<Service[]>([]);
  const [family, setFamily] = useState<FamilyMember[]>([]);
  const [addresses, setAddresses] = useState<Address[]>([]);
  const [selectedServiceSlug, setSelectedServiceSlug] = useState(initialService ?? "");
  const [familyMemberId, setFamilyMemberId] = useState("");
  const [addressId, setAddressId] = useState("");
  const [newAddress, setNewAddress] = useState({ label: "Home", recipientName: "", addressLine1: "", locality: "", city: "", state: "", postalCode: "" });
  const [scheduledStart, setScheduledStart] = useState("");
  const [durationMinutes, setDurationMinutes] = useState(60);
  const [requirements, setRequirements] = useState("");
  const [error, setError] = useState("");
  const [booking, setBooking] = useState<Booking | null>(null);
  const [saving, setSaving] = useState(false);

  useEffect(() => { Promise.all([apiFetch<Service[]>("/services"), apiFetch<FamilyMember[]>("/customer/family-members"), apiFetch<Address[]>("/customer/addresses")]).then(([catalog, members, savedAddresses]) => { setServices(catalog); setFamily(members); setAddresses(savedAddresses); }).catch((cause: Error) => setError(cause.message)); }, []);
  const service = useMemo(() => services.find((item) => item.slug === selectedServiceSlug), [services, selectedServiceSlug]);
  const continueStep = () => { setError(""); if (step === 1 && !service) return setError("Choose a service to continue."); if (step === 2 && !addressId) return setError("Save or choose an address to continue."); if (step === 3 && (!scheduledStart || !durationMinutes)) return setError("Choose a date, time, and duration."); setStep((current) => Math.min(steps.length - 1, current + 1)); };
  const saveAddress = async () => { try { const created = await apiFetch<Address>("/customer/addresses", { method: "POST", body: JSON.stringify(newAddress) }); setAddresses((current) => [...current, created]); setAddressId(created.id); } catch (cause) { setError((cause as Error).message); } };
  const create = async () => { if (!service || !addressId) return; setSaving(true); setError(""); try { setBooking(await apiFetch<Booking>("/bookings", { method: "POST", headers: { "idempotency-key": `booking-${Date.now()}` }, body: JSON.stringify({ familyMemberId: familyMemberId || undefined, serviceSlug: service.slug, addressId, scheduledStart: new Date(scheduledStart).toISOString(), durationMinutes, requirements: requirements || undefined }) })); } catch (cause) { setError((cause as Error).message); } finally { setSaving(false); } };
  if (booking) return <Card className="confirmation-card"><p className="eyebrow">Request received</p><h1>Your booking is ready for the next step.</h1><p className="lede">{booking.serviceName} · {new Date(booking.scheduledStart).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</p><Notice>Reference {booking.reference}. Payment has not been collected. Provider assignment will happen after confirmation.</Notice><div className="hero-actions"><Link href={`/customer/bookings/${booking.id}`}><Button size="lg">View booking</Button></Link><Link href="/customer/services"><Button variant="secondary" size="lg">Browse services</Button></Link></div></Card>;
  if (!services.length) return <EmptyState title="Preparing your booking">We’re loading the service options and saved details.</EmptyState>;
  return <div className="wizard"><div className="stepper" aria-label="Booking progress">{steps.map((label, index) => <div className={index <= step ? "step active" : "step"} key={label}><span>{index + 1}</span><small>{label}</small></div>)}</div>{error && <Notice tone="error">{error}</Notice>}<Card className="wizard-card"><p className="eyebrow">Step {step + 1} of {steps.length}</p>
    {step === 0 && <><h1>Who is this for?</h1><p className="muted">You can arrange support for yourself or someone you care for.</p><div className="choice-grid"><button className={!familyMemberId ? "choice selected" : "choice"} onClick={() => setFamilyMemberId("")} type="button"><strong>Myself</strong><span>I’ll be receiving the assistance.</span></button>{family.map((member) => <button className={familyMemberId === member.id ? "choice selected" : "choice"} onClick={() => setFamilyMemberId(member.id)} key={member.id} type="button"><strong>{member.name}</strong><span>{member.relationship}</span></button>)}</div></>}
    {step === 1 && <><h1>Choose the kind of help</h1><div className="choice-list">{services.map((item) => <button className={selectedServiceSlug === item.slug ? "choice selected" : "choice"} onClick={() => { setSelectedServiceSlug(item.slug); setDurationMinutes(item.durationOptionsMinutes[0] ?? 60); }} key={item.slug} type="button"><strong>{item.name}</strong><span>{item.shortDescription}</span></button>)}</div></>}
    {step === 2 && <><h1>Where should we meet?</h1><p className="muted">Choose a saved address or add one for this request.</p>{addresses.length > 0 && <select className="select" value={addressId} onChange={(event) => setAddressId(event.target.value)}><option value="">Choose a saved address</option>{addresses.map((address) => <option value={address.id} key={address.id}>{address.label} · {address.city}</option>)}</select>}<div className="address-form"><Field label="Label" value={newAddress.label} onChange={(event) => setNewAddress({ ...newAddress, label: event.target.value })} /><Field label="Recipient name" value={newAddress.recipientName} onChange={(event) => setNewAddress({ ...newAddress, recipientName: event.target.value })} /><Field label="Address line" value={newAddress.addressLine1} onChange={(event) => setNewAddress({ ...newAddress, addressLine1: event.target.value })} /><Field label="Locality" value={newAddress.locality} onChange={(event) => setNewAddress({ ...newAddress, locality: event.target.value })} /><Field label="City" value={newAddress.city} onChange={(event) => setNewAddress({ ...newAddress, city: event.target.value })} /><Field label="State" value={newAddress.state} onChange={(event) => setNewAddress({ ...newAddress, state: event.target.value })} /><Field label="Postal code" inputMode="numeric" value={newAddress.postalCode} onChange={(event) => setNewAddress({ ...newAddress, postalCode: event.target.value })} /></div><Button variant="secondary" type="button" onClick={saveAddress}>Save this address</Button></>}
    {step === 3 && service && <><h1>When should we be there?</h1><div className="address-form"><Field label="Date and time" type="datetime-local" value={scheduledStart} onChange={(event) => setScheduledStart(event.target.value)} min={new Date(Date.now() + 3600000).toISOString().slice(0, 16)} /><div className="field"><label htmlFor="duration">Duration</label><select id="duration" className="select" value={durationMinutes} onChange={(event) => setDurationMinutes(Number(event.target.value))}>{service.durationOptionsMinutes.map((minutes) => <option value={minutes} key={minutes}>{minutes / 60} {minutes === 60 ? "hour" : "hours"}</option>)}</select></div></div></>}
    {step === 4 && <><h1>Anything helpful to know?</h1><p className="muted">Share practical instructions only. Please don’t include unnecessary medical, financial, or identity information.</p><textarea className="textarea" maxLength={1000} value={requirements} onChange={(event) => setRequirements(event.target.value)} placeholder="Where to meet, mobility considerations, appointment details, pet behavior, or a shopping list." /><p className="field-message">{requirements.length}/1000</p></>}
    {step === 5 && service && <><h1>Review your request</h1><div className="review-list"><div><span>Service</span><strong>{service.name}</strong></div><div><span>Recipient</span><strong>{family.find((member) => member.id === familyMemberId)?.name ?? "Myself"}</strong></div><div><span>When</span><strong>{scheduledStart ? new Date(scheduledStart).toLocaleString("en-IN") : "Not selected"}</strong></div><div><span>Duration</span><strong>{durationMinutes / 60} hours</strong></div><div><span>Payment</span><strong>Not collected yet</strong></div></div><div className="price-summary"><span>Estimated total</span><strong>{formatINR(service.basePriceMinor + Math.max(0, durationMinutes / 60 - 1) * service.hourlyRateMinor)}</strong></div></>}
    <div className="wizard-actions"><Button variant="quiet" type="button" disabled={step === 0} onClick={() => setStep((current) => current - 1)}>Back</Button>{step < 5 ? <Button type="button" onClick={continueStep}>Continue</Button> : <Button type="button" onClick={create} disabled={saving}>{saving ? "Creating…" : "Create booking request"}</Button>}</div>
  </Card></div>;
}
