"use client";

import { useEffect, useState } from "react";
import { apiFetch, type Address, type FamilyMember } from "../../lib/api";
import { Button } from "../ui/Button";
import { Card } from "../ui/Surface";
import { EmptyState, Notice } from "../ui/Feedback";
import { Field } from "../ui/Field";

export function PeoplePlaces() {
  const [family, setFamily] = useState<FamilyMember[]>([]); const [addresses, setAddresses] = useState<Address[]>([]); const [error, setError] = useState("");
  const [member, setMember] = useState({ name: "", relationship: "", phone: "" }); const [address, setAddress] = useState({ label: "", recipientName: "", addressLine1: "", locality: "", city: "", state: "", postalCode: "" });
  useEffect(() => { Promise.all([apiFetch<FamilyMember[]>("/customer/family-members"), apiFetch<Address[]>("/customer/addresses")]).then(([people, saved]) => { setFamily(people); setAddresses(saved); }).catch((cause: Error) => setError(cause.message)); }, []);
  const addMember = async (event: React.FormEvent) => { event.preventDefault(); try { const created = await apiFetch<FamilyMember>("/customer/family-members", { method: "POST", body: JSON.stringify(member) }); setFamily((items) => [...items, created]); setMember({ name: "", relationship: "", phone: "" }); } catch (cause) { setError((cause as Error).message); } };
  const addAddress = async (event: React.FormEvent) => { event.preventDefault(); try { const created = await apiFetch<Address>("/customer/addresses", { method: "POST", body: JSON.stringify(address) }); setAddresses((items) => [...items, created]); setAddress({ label: "", recipientName: "", addressLine1: "", locality: "", city: "", state: "", postalCode: "" }); } catch (cause) { setError((cause as Error).message); } };
  return <>{error && <Notice tone="error">{error}</Notice>}<div className="content-grid"><Card eyebrow="People you care for" title="Family members"><form className="compact-form" onSubmit={addMember}><Field label="Name" value={member.name} onChange={(event) => setMember({ ...member, name: event.target.value })} required /><Field label="Relationship" value={member.relationship} onChange={(event) => setMember({ ...member, relationship: event.target.value })} required /><Field label="Phone (optional)" value={member.phone} onChange={(event) => setMember({ ...member, phone: event.target.value })} /><Button type="submit" size="sm">Add person</Button></form>{family.length ? family.map((item) => <div className="list-row" key={item.id}><span><strong>{item.name}</strong><br /><span className="list-meta">{item.relationship}</span></span></div>) : <EmptyState title="No saved people">Add someone you regularly arrange support for.</EmptyState>}</Card><Card eyebrow="Saved places" title="Addresses"><form className="compact-form" onSubmit={addAddress}><Field label="Label" value={address.label} onChange={(event) => setAddress({ ...address, label: event.target.value })} required /><Field label="Recipient name" value={address.recipientName} onChange={(event) => setAddress({ ...address, recipientName: event.target.value })} required /><Field label="Address line" value={address.addressLine1} onChange={(event) => setAddress({ ...address, addressLine1: event.target.value })} required /><Field label="Locality" value={address.locality} onChange={(event) => setAddress({ ...address, locality: event.target.value })} required /><Field label="City" value={address.city} onChange={(event) => setAddress({ ...address, city: event.target.value })} required /><Field label="State" value={address.state} onChange={(event) => setAddress({ ...address, state: event.target.value })} required /><Field label="Postal code" value={address.postalCode} onChange={(event) => setAddress({ ...address, postalCode: event.target.value })} required /><Button type="submit" size="sm">Save address</Button></form>{addresses.length ? addresses.map((item) => <div className="list-row" key={item.id}><span><strong>{item.label}</strong><br /><span className="list-meta">{item.addressLine1}, {item.city}</span></span></div>) : <EmptyState title="No saved addresses">Save a place to make your next request simpler.</EmptyState>}</Card></div></>;
}
