import type { FastifyInstance, FastifyRequest } from "fastify";
import { z, ZodError } from "zod";
import { config } from "../config.js";
import { AppError, forbidden, unauthorized } from "../errors.js";
import { safetyService } from "./service.js";
function parse<T>(schema: z.ZodType<T>, value: unknown) { try { return schema.parse(value); } catch (error) { if (error instanceof ZodError) throw new AppError("VALIDATION_ERROR", error.issues[0]?.message ?? "Invalid request.", 400); throw error; } }
function provider(request: FastifyRequest) { const value = request.headers["x-provider-id"]; if (typeof value === "string" && value) return value; if (config.NODE_ENV !== "production") return "provider-demo-approved"; throw unauthorized(); }
function customer(request: FastifyRequest) { const value = request.headers["x-customer-id"]; if (typeof value === "string" && value) return value; if (config.NODE_ENV !== "production") return "customer-demo"; throw unauthorized(); }
function admin(request: FastifyRequest) { const role = request.headers["x-role"]; if (role !== "ADMIN" && role !== "SUPPORT" && config.NODE_ENV === "production") throw forbidden(); return typeof request.headers["x-actor-id"] === "string" ? request.headers["x-actor-id"] : "admin-demo"; }
export function registerSafetyRoutes(app: FastifyInstance) { app.post<{ Params: { id: string } }>("/api/v1/provider/bookings/:id/tracking/start", async (request) => ({ data: safetyService.start(provider(request), request.params.id) })); app.post<{ Params: { id: string } }>("/api/v1/provider/tracking/:id/stop", async (request) => ({ data: safetyService.stop(provider(request), request.params.id) })); app.post<{ Params: { id: string } }>("/api/v1/provider/bookings/:id/location", async (request) => ({ data: safetyService.addLocation(provider(request), request.params.id, parse(z.object({ latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180), accuracyMeters: z.number().positive().optional() }), request.body)) })); app.get<{ Params: { id: string } }>("/api/v1/customer/bookings/:id/location", async (request) => ({ data: safetyService.view(customer(request), request.params.id) })); app.post<{ Params: { id: string } }>("/api/v1/bookings/:id/emergency", async (request) => ({ data: safetyService.emergency(customer(request), request.params.id, parse(z.object({ description: z.string().trim().min(5).max(500), severity: z.enum(["LOW", "MEDIUM", "HIGH", "EMERGENCY"]).default("EMERGENCY") }), request.body).description) })); app.get("/api/v1/admin/incidents", async (request) => ({ data: safetyService.listIncidents(), meta: { actor: admin(request) } })); app.post<{ Params: { id: string } }>("/api/v1/admin/incidents/:id/resolve", async (request) => ({ data: safetyService.resolve(admin(request), request.params.id) })); }
