import { randomUUID } from "node:crypto";
import { AppError } from "../errors.js";
import { customerStore } from "../customer/store.js";
import { providerRepository } from "../provider/repository.js";
import type { Incident, LocationPoint, TrackingSession } from "./types.js";
export class SafetyService { private sessions = new Map<string, TrackingSession>(); private points: LocationPoint[] = []; private incidents: Incident[] = [];
  private booking(bookingId: string) { const booking = customerStore.getBookingForSystem(bookingId); if (!booking.assignedProviderId) throw new AppError("BOOKING_NOT_ASSIGNED", "Safety tools are available after provider assignment.", 409); return booking; }
  start(providerId: string, bookingId: string) { const booking = this.booking(bookingId); if (booking.assignedProviderId !== providerId) throw new AppError("FORBIDDEN", "Only the assigned provider can start tracking.", 403); const current = [...this.sessions.values()].find((item) => item.bookingId === bookingId && item.status === "ACTIVE"); if (current) return current; const item: TrackingSession = { id: randomUUID(), bookingId, providerId, status: "ACTIVE", startedAt: new Date().toISOString() }; this.sessions.set(item.id, item); return item; }
  stop(providerId: string, sessionId: string) { const item = this.sessions.get(sessionId); if (!item) throw new AppError("NOT_FOUND", "Tracking session not found.", 404); if (item.providerId !== providerId) throw new AppError("FORBIDDEN", "Tracking session is not available to this provider.", 403); item.status = "STOPPED"; item.stoppedAt = new Date().toISOString(); return item; }
  addLocation(providerId: string, bookingId: string, input: { latitude: number; longitude: number; accuracyMeters?: number | undefined }) { const booking = this.booking(bookingId); if (booking.assignedProviderId !== providerId) throw new AppError("FORBIDDEN", "Only the assigned provider can share location.", 403); const active = [...this.sessions.values()].some((item) => item.bookingId === bookingId && item.providerId === providerId && item.status === "ACTIVE"); if (!active) throw new AppError("TRACKING_NOT_ACTIVE", "Start tracking before sharing location.", 409); const point: LocationPoint = { id: randomUUID(), bookingId, providerId, ...input, capturedAt: new Date().toISOString() }; this.points.push(point); return point; }
  view(customerId: string, bookingId: string) { const booking = customerStore.getBooking(customerId, bookingId); if (!booking.assignedProviderId) return { tracking: undefined, latest: undefined }; const tracking = [...this.sessions.values()].find((item) => item.bookingId === bookingId && item.status === "ACTIVE"); const latest = this.points.filter((point) => point.bookingId === bookingId).at(-1); return { tracking, latest }; }
  emergency(reporterId: string, bookingId: string, description: string, severity: Incident["severity"] = "EMERGENCY") { const booking = customerStore.getBookingForSystem(bookingId); if (booking.customerId !== reporterId && booking.assignedProviderId !== reporterId) throw new AppError("FORBIDDEN", "Only the customer or assigned provider can report an incident.", 403); const location = this.points.filter((point) => point.bookingId === bookingId).at(-1); const item: Incident = { id: randomUUID(), bookingId, reporterId, severity, status: "OPEN", description, locationId: location?.id, createdAt: new Date().toISOString() }; this.incidents.push(item); customerStore.addEvent(booking, "EMERGENCY_REPORTED", "A safety incident was reported. Operations has been alerted.", true); return item; }
  listIncidents() { return this.incidents.map((item) => ({ ...item })); }
  resolve(actorId: string, id: string) { const item = this.incidents.find((incident) => incident.id === id); if (!item) throw new AppError("NOT_FOUND", "Incident not found.", 404); item.status = "RESOLVED"; item.resolvedAt = new Date().toISOString(); const booking = customerStore.getBookingForSystem(item.bookingId); void providerRepository.audit(booking.assignedProviderId ?? item.reporterId, actorId, "INCIDENT_RESOLVED"); return item; }
}
export const safetyService = new SafetyService();
