"use client";

import { useEffect, useState } from "react";
import { apiFetch } from "../../lib/api";
import { Button } from "../ui/Button";
import { Badge, Card } from "../ui/Surface";
import { Notice, EmptyState } from "../ui/Feedback";

type Request = { id: string; bookingId: string; status: string; expiresAt?: string; matchingScore?: number; booking?: { serviceName: string; scheduledStart: string; durationMinutes: number; area: string; requirements?: string } };
export function ProviderRequests() { const [items, setItems] = useState<Request[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(""); const load = () => apiFetch<Request[]>("/provider/requests").then(setItems).catch((cause: Error) => setError(cause.message)); useEffect(() => { void load(); }, []); const act = async (id: string, action: "accept" | "decline") => { setBusy(id); try { const init: RequestInit = { method: "POST" }; if (action === "decline") init.body = JSON.stringify({ reason: "other" }); await apiFetch(`/provider/requests/${id}/${action}`, init); await load(); } catch (cause) { setError((cause as Error).message); } finally { setBusy(""); } }; if (error) return <Notice tone="error">{error}</Notice>; return <><div className="page-heading"><div><p className="eyebrow">Provider requests</p><h1>Requests that fit your schedule</h1><p className="muted">Only approved, eligible and available requests are shown.</p></div></div>{!items.length ? <Card><EmptyState title="No requests waiting">New requests will appear here when a customer needs support in your service area.</EmptyState></Card> : <div className="content-grid">{items.map((item) => <Card key={item.id} eyebrow={item.status} title={item.booking?.serviceName ?? "Assistance request"}><p className="card-copy">{item.booking ? `${new Date(item.booking.scheduledStart).toLocaleString("en-IN")} · ${item.booking.durationMinutes / 60} hours · ${item.booking.area}` : "Loading request details"}</p>{item.booking?.requirements && <p className="muted">Important: {item.booking.requirements}</p>}<Badge tone={item.status === "SENT" || item.status === "VIEWED" ? "warning" : "neutral"}>{item.status}</Badge>{["SENT", "VIEWED"].includes(item.status) && <div className="button-row"><Button onClick={() => act(item.id, "accept")} disabled={busy === item.id}>{busy === item.id ? "Working…" : "Accept request"}</Button><Button variant="secondary" onClick={() => act(item.id, "decline")} disabled={Boolean(busy)}>Decline</Button></div>}</Card>)}</div>}</>; }
