"use client";

import { useEffect, useState } from "react";
import { apiFetch } from "../../lib/api";
import { Button } from "../ui/Button";
import { Badge, Card } from "../ui/Surface";
import { Notice } from "../ui/Feedback";
import { Field } from "../ui/Field";

type Profile = { displayName: string; bio?: string; languages: string[]; experienceSummary?: string; timezone: string; onboardingStatus: string; accountStatus: string };
type Service = { serviceSlug: string; eligibilityStatus: string };
type Availability = { id: string; kind: string; dayOfWeek?: number; startTime?: string; endTime?: string; timezone: string; startsAt?: string; endsAt?: string };
const serviceOptions = ["hospital-appointment-companion", "elder-companion", "pet-assistance", "everyday-assistance"];

export function ProviderProfileForm() {
  const [profile, setProfile] = useState<Profile | null>(null); const [form, setForm] = useState({ displayName: "", bio: "", experienceSummary: "", languages: "English, Hindi", timezone: "Asia/Kolkata" }); const [error, setError] = useState(""); const [saved, setSaved] = useState(false);
  useEffect(() => { apiFetch<Profile>("/provider/profile").then((data) => { setProfile(data); setForm({ displayName: data.displayName, bio: data.bio ?? "", experienceSummary: data.experienceSummary ?? "", languages: data.languages.join(", "), timezone: data.timezone }); }).catch((cause: Error) => setError(cause.message)); }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaved(false); try { const data = await apiFetch<Profile>("/provider/profile", { method: "PATCH", body: JSON.stringify({ ...form, languages: form.languages.split(",").map((value) => value.trim()).filter(Boolean) }) }); setProfile(data); setSaved(true); } catch (cause) { setError((cause as Error).message); } };
  if (error) return <Notice tone="error">{error}</Notice>; if (!profile) return <Card><p className="muted">Loading your provider profile…</p></Card>;
  return <div className="provider-stack">{saved && <Notice>Profile saved. Trust and verification fields remain controlled by operations.</Notice>}<Card eyebrow="Profile status" title="Tell customers what you can help with"><div className="status-line"><Badge tone={profile.onboardingStatus === "APPROVED" ? "success" : "warning"}>{profile.onboardingStatus.replaceAll("_", " ")}</Badge><span className="muted">Account: {profile.accountStatus.toLowerCase()}</span></div><form className="compact-form" onSubmit={save}><Field label="Display name" value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })} required /><Field label="Languages" hint="Separate languages with commas." value={form.languages} onChange={(event) => setForm({ ...form, languages: event.target.value })} /><div className="field"><label htmlFor="provider-bio">Short bio</label><textarea id="provider-bio" className="textarea" value={form.bio} onChange={(event) => setForm({ ...form, bio: event.target.value })} maxLength={1000} /></div><div className="field"><label htmlFor="provider-experience">Experience summary</label><textarea id="provider-experience" className="textarea" value={form.experienceSummary} onChange={(event) => setForm({ ...form, experienceSummary: event.target.value })} maxLength={500} /></div><Field label="Timezone" hint="Use an IANA timezone, such as Asia/Kolkata." value={form.timezone} onChange={(event) => setForm({ ...form, timezone: event.target.value })} /><Button type="submit">Save profile</Button></form></Card></div>;
}

export function ProviderServicesForm() { const [selected, setSelected] = useState<string[]>([]); const [services, setServices] = useState<Service[]>([]); const [error, setError] = useState(""); useEffect(() => { apiFetch<Service[]>("/provider/services").then((items) => { setServices(items); setSelected(items.map((item) => item.serviceSlug)); }).catch((cause: Error) => setError(cause.message)); }, []); const save = async () => { try { setServices(await apiFetch<Service[]>("/provider/services", { method: "PUT", body: JSON.stringify({ serviceSlugs: selected }) })); } catch (cause) { setError((cause as Error).message); } }; return <Card eyebrow="Service categories" title="Choose the support you’re prepared to offer">{error && <Notice tone="error">{error}</Notice>}<div className="choice-list">{serviceOptions.map((slug) => <label className="check-row" key={slug}><input type="checkbox" checked={selected.includes(slug)} onChange={(event) => setSelected((items) => event.target.checked ? [...items, slug] : items.filter((item) => item !== slug))} /><span>{slug.replaceAll("-", " ")}</span><small>{services.find((item) => item.serviceSlug === slug)?.eligibilityStatus ?? "not selected"}</small></label>)}</div><Button onClick={save}>Save services</Button><p className="field-message">Eligibility remains pending until operations verifies the relevant service requirements.</p></Card>; }

export function ProviderAvailabilityForm() { const [items, setItems] = useState<Availability[]>([]); const [form, setForm] = useState({ dayOfWeek: 1, startTime: "09:00", endTime: "18:00", timezone: "Asia/Kolkata" }); const [error, setError] = useState(""); useEffect(() => { apiFetch<Availability[]>("/provider/availability").then(setItems).catch((cause: Error) => setError(cause.message)); }, []); const add = async (event: React.FormEvent) => { event.preventDefault(); try { const created = await apiFetch<Availability>("/provider/availability", { method: "POST", body: JSON.stringify({ kind: "WEEKLY", ...form }) }); setItems((current) => [...current, created]); } catch (cause) { setError((cause as Error).message); } }; const remove = async (id: string) => { await apiFetch<void>(`/provider/availability/${id}`, { method: "DELETE" }); setItems((current) => current.filter((item) => item.id !== id)); }; return <div className="provider-stack">{error && <Notice tone="error">{error}</Notice>}<Card eyebrow="Weekly schedule" title="When are you generally available?"><form className="address-form" onSubmit={add}><div className="field"><label htmlFor="day">Day</label><select id="day" className="select" value={form.dayOfWeek} onChange={(event) => setForm({ ...form, dayOfWeek: Number(event.target.value) })}>{["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"].map((day, index) => <option value={index + 1} key={day}>{day}</option>)}</select></div><Field label="Start" type="time" value={form.startTime} onChange={(event) => setForm({ ...form, startTime: event.target.value })} /><Field label="End" type="time" value={form.endTime} onChange={(event) => setForm({ ...form, endTime: event.target.value })} /><Field label="Timezone" value={form.timezone} onChange={(event) => setForm({ ...form, timezone: event.target.value })} /><Button type="submit">Add time block</Button></form></Card><Card eyebrow="Saved availability" title="Your schedule"><div className="booking-list">{items.length ? items.map((item) => <div className="list-row" key={item.id}><span><strong>{item.kind === "WEEKLY" ? `Day ${item.dayOfWeek}` : "Blackout"}</strong><br /><span className="list-meta">{item.startTime}–{item.endTime} · {item.timezone}</span></span><Button variant="quiet" size="sm" onClick={() => remove(item.id)}>Remove</Button></div>) : <p className="muted">No availability blocks yet.</p>}</div></Card></div>; }

export function ProviderVerification() { const [documents, setDocuments] = useState<{ id: string; documentType: string; status: string; uploadedAt: string }[]>([]); const [error, setError] = useState(""); const [documentType, setDocumentType] = useState("IDENTITY"); const [storageRef, setStorageRef] = useState(""); useEffect(() => { apiFetch<typeof documents>("/provider/documents").then(setDocuments).catch((cause: Error) => setError(cause.message)); }, []); const submit = async (event: React.FormEvent) => { event.preventDefault(); try { const item = await apiFetch<typeof documents[number]>("/provider/documents", { method: "POST", body: JSON.stringify({ documentType, storageRef }) }); setDocuments((items) => [...items, item]); setStorageRef(""); } catch (cause) { setError((cause as Error).message); } }; return <div className="provider-stack">{error && <Notice tone="error">{error}</Notice>}<Card eyebrow="Verification" title="Build trust carefully"><p className="card-copy">Verification is reviewed by operations. Development uploads use private storage references and do not represent a real background check.</p><form className="compact-form" onSubmit={submit}><Field label="Document type" value={documentType} onChange={(event) => setDocumentType(event.target.value)} /><Field label="Private storage reference" hint="Use a private:// reference in development. Never paste a public URL." value={storageRef} onChange={(event) => setStorageRef(event.target.value)} required /><Button type="submit">Submit metadata</Button></form></Card><Card eyebrow="Submitted" title="Document status"><div className="booking-list">{documents.length ? documents.map((item) => <div className="list-row" key={item.id}><span><strong>{item.documentType}</strong><br /><span className="list-meta">Submitted {new Date(item.uploadedAt).toLocaleDateString("en-IN")}</span></span><Badge tone={item.status === "VERIFIED" ? "success" : "warning"}>{item.status}</Badge></div>) : <p className="muted">No document metadata submitted.</p>}</div></Card></div>; }
