import { randomUUID } from "node:crypto";
import { AppError } from "../errors.js";
import { customerStore } from "../customer/store.js";
import { SandboxPaymentAdapter } from "./adapter.js";
import type { Earnings, Payment, Refund } from "./types.js";
import { notificationService } from "../notifications/service.js";
import { config } from "../config.js";
export class PaymentService { private payments = new Map<string, Payment>(); private byKey = new Map<string, string>(); private webhooks = new Set<string>(); private refunds: Refund[] = []; private earnings = new Map<string, Earnings>(); readonly adapter = new SandboxPaymentAdapter(config.PAYMENT_WEBHOOK_SECRET);
  createOrder(customerId: string, bookingId: string, idempotencyKey: string) { const booking = customerStore.getBooking(customerId, bookingId); if (booking.state !== "PENDING_PAYMENT") throw new AppError("PAYMENT_NOT_ALLOWED", "This booking is not ready for payment.", 409); const existingId = this.byKey.get(`${customerId}:${idempotencyKey}`); if (existingId) return this.payments.get(existingId)!; const now = new Date().toISOString(); const payment: Payment = { id: randomUUID(), bookingId, customerId, provider: "razorpay-sandbox", providerOrderId: `order_${randomUUID()}`, status: "CREATED", amountMinor: booking.estimateAmountMinor, currency: booking.currency, idempotencyKey, createdAt: now, updatedAt: now }; this.payments.set(payment.id, payment); this.byKey.set(`${customerId}:${idempotencyKey}`, payment.id); return payment; }
  get(customerId: string, paymentId: string) { const payment = this.payments.get(paymentId); if (!payment) throw new AppError("NOT_FOUND", "Payment not found.", 404); if (payment.customerId !== customerId) throw new AppError("FORBIDDEN", "Payment is not available to this account.", 403); return payment; }
  verify(customerId: string, paymentId: string, input: { paymentId: string; signature: string }) { const payment = this.get(customerId, paymentId); if (!this.adapter.verifyPayment({ orderId: payment.providerOrderId, paymentId: input.paymentId, signature: input.signature })) throw new AppError("PAYMENT_VERIFICATION_FAILED", "Payment verification failed.", 400); payment.providerPaymentId = input.paymentId; payment.status = "CAPTURED"; payment.updatedAt = new Date().toISOString(); const booking = customerStore.getBookingForSystem(payment.bookingId); if (booking.state === "PENDING_PAYMENT") { booking.state = "PAID"; customerStore.addEvent(booking, "PAYMENT_CONFIRMED", "Payment has been confirmed."); notificationService.emit(customerId, `payment-confirmed:${payment.id}`, "Payment confirmed", "Your booking payment has been confirmed."); } return payment; }
  webhook(rawBody: string, signature: string, eventId: string, eventType: string, payload: { paymentId: string; orderId: string; status: "CAPTURED" | "FAILED" }) { if (!this.adapter.verifyWebhook(rawBody, signature)) throw new AppError("INVALID_WEBHOOK", "Webhook signature is invalid.", 400); if (this.webhooks.has(eventId)) return { duplicate: true }; this.webhooks.add(eventId); const payment = [...this.payments.values()].find((item) => item.providerOrderId === payload.orderId); if (!payment) throw new AppError("PAYMENT_NOT_FOUND", "Webhook order is not recognized.", 404); payment.providerPaymentId = payload.paymentId; payment.status = payload.status; payment.updatedAt = new Date().toISOString(); if (payload.status === "CAPTURED") { const booking = customerStore.getBookingForSystem(payment.bookingId); if (booking.state === "PENDING_PAYMENT") { booking.state = "PAID"; customerStore.addEvent(booking, "PAYMENT_CONFIRMED", "Payment has been confirmed."); } } return { duplicate: false, payment }; }
  refund(customerId: string, paymentId: string, reason: string) { const payment = this.get(customerId, paymentId); if (!["CAPTURED", "AUTHORIZED"].includes(payment.status)) throw new AppError("REFUND_NOT_ALLOWED", "This payment cannot be refunded.", 409); const booking = customerStore.getBookingForSystem(payment.bookingId); if (["SERVICE_STARTED", "SERVICE_COMPLETED"].includes(booking.state)) throw new AppError("REFUND_NOT_ALLOWED", "Refunds are not available after service starts.", 409); const refund: Refund = { id: randomUUID(), paymentId, amountMinor: payment.amountMinor, reason, status: "COMPLETED", createdAt: new Date().toISOString() }; this.refunds.push(refund); payment.status = "REFUNDED"; payment.updatedAt = new Date().toISOString(); customerStore.addEvent(booking, "REFUND_COMPLETED", "Payment refund recorded."); return refund; }
  recordEarnings(bookingId: string, providerId: string, commissionRate = 0.2) { const booking = customerStore.getBookingForSystem(bookingId); const existing = this.earnings.get(`${bookingId}:${providerId}`); if (existing) return existing; const commissionMinor = Math.round(booking.estimateAmountMinor * commissionRate); const item = { bookingId, providerId, grossMinor: booking.estimateAmountMinor, commissionMinor, netMinor: booking.estimateAmountMinor - commissionMinor, currency: booking.currency }; this.earnings.set(`${bookingId}:${providerId}`, item); return item; }
  listPayments() { return [...this.payments.values()]; } listEarnings() { return [...this.earnings.values()]; }
}
export const paymentService = new PaymentService();
