import { Button } from "../ui/Button";
import { Badge, Card } from "../ui/Surface";
import { EmptyState } from "../ui/Feedback";

export function CustomerDashboard() { return <><div className="page-heading"><div><p className="eyebrow">Good morning</p><h1>Your care space</h1><p className="muted">A clear view of the support you’ve arranged.</p></div><Button>Arrange support</Button></div><div className="stats-grid"><Card><span className="stat-value">0</span><span className="stat-label">Upcoming bookings</span></Card><Card><span className="stat-value">—</span><span className="stat-label">Active support</span></Card><Card><span className="stat-value">0</span><span className="stat-label">People you care for</span></Card></div><div className="content-grid"><Card eyebrow="Next step" title="Start with what matters"><EmptyState title="Nothing scheduled yet">When you’re ready, we’ll help you arrange thoughtful non-medical assistance.</EmptyState></Card><Card eyebrow="Your space" title="Keep things close"><div className="list-row"><span><span className="list-title">People &amp; places</span><br /><span className="list-meta">Dependents and saved addresses</span></span><Badge>Set up later</Badge></div><div className="list-row"><span><span className="list-title">Support</span><br /><span className="list-meta">We’re here when you need us</span></span><Badge tone="success">Available</Badge></div></Card></div></>; }

export function ProviderDashboard() { return <><div className="page-heading"><div><p className="eyebrow">Provider space</p><h1>Today, at a glance</h1><p className="muted">Your work starts with clarity and trust.</p></div><Button variant="secondary">Update availability</Button></div><div className="stats-grid"><Card><span className="stat-value">0</span><span className="stat-label">Requests waiting</span></Card><Card><span className="stat-value">—</span><span className="stat-label">Today’s schedule</span></Card><Card><span className="stat-value"><Badge tone="warning">Pending</Badge></span><span className="stat-label">Verification</span></Card></div><Card eyebrow="Your next step" title="Complete your provider profile"><p className="card-copy">Your verification status will appear here once your profile and required documents are ready.</p><Button variant="secondary">View verification</Button></Card></>; }

export function OperationsDashboard() { return <><div className="page-heading"><div><p className="eyebrow">Operations</p><h1>Keep every detail moving calmly.</h1><p className="muted">A focused view of trust, support, and service health.</p></div></div><div className="stats-grid"><Card><span className="stat-value">0</span><span className="stat-label">Open bookings</span></Card><Card><span className="stat-value">0</span><span className="stat-label">Pending verifications</span></Card><Card><span className="stat-value">0</span><span className="stat-label">Open incidents</span></Card></div><Card eyebrow="Operations queue" title="Nothing requires attention"><EmptyState title="All clear for now">New verification, support, and safety items will appear here.</EmptyState></Card></>; }
