import { AppError } from "../errors.js";
import { customerStore } from "../customer/store.js";
import { providerRepository } from "../provider/repository.js";
import type { ProviderProfile, ProviderRequest } from "../provider/types.js";

export const matchingConfig = { maxActiveRequests: 3, requestExpiryMinutes: 10 } as const;

type Candidate = { provider: ProviderProfile; score: number; reasons: string[] };
let assignmentQueue = Promise.resolve();

function dayInZone(iso: string, timezone: string) { const parts = new Intl.DateTimeFormat("en-US", { timeZone: timezone, weekday: "short", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(iso)); const weekdays: Record<string, number> = { Sun: 7, Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6 }; const weekday = weekdays[parts.find((part) => part.type === "weekday")?.value ?? ""] ?? 0; const hour = parts.find((part) => part.type === "hour")?.value ?? "00"; const minute = parts.find((part) => part.type === "minute")?.value ?? "00"; return { weekday, time: `${hour}:${minute}` }; }

function overlaps(start: string, durationMinutes: number, otherStart: string, otherDuration: number) { const a = Date.parse(start); const b = Date.parse(otherStart); return a < b + otherDuration * 60_000 && b < a + durationMinutes * 60_000; }

export class MatchingService {
  private async eligibleProviders(bookingId: string): Promise<Candidate[]> {
    const booking = customerStore.getBookingForSystem(bookingId); const address = customerStore.getAddressForSystem(booking.addressId); const allBookings = customerStore.listAllBookings(); const candidates: Candidate[] = [];
    for (const provider of await providerRepository.listProviders()) {
      if (!(await providerRepository.isEligible(provider.userId, booking.serviceSlug))) continue;
      const area = provider.serviceAreas.some((item) => item.city.toLowerCase() === address.city.toLowerCase() && (!item.locality || item.locality.toLowerCase() === address.locality.toLowerCase()));
      if (!area) continue;
      const blocks = await providerRepository.listAvailability(provider.userId); const local = dayInZone(booking.scheduledStart, provider.timezone); const startMinutes = Number(local.time.slice(0, 2)) * 60 + Number(local.time.slice(3)); const endMinutes = startMinutes + booking.durationMinutes; const available = blocks.some((block) => block.active && block.kind === "WEEKLY" && block.dayOfWeek === local.weekday && block.startTime && block.endTime && startMinutes >= Number(block.startTime.slice(0, 2)) * 60 + Number(block.startTime.slice(3)) && endMinutes <= Number(block.endTime.slice(0, 2)) * 60 + Number(block.endTime.slice(3)));
      if (!available) continue;
      const blackout = blocks.some((block) => block.active && block.kind === "BLACKOUT" && block.startsAt && block.endsAt && Date.parse(booking.scheduledStart) < Date.parse(block.endsAt) && Date.parse(block.startsAt) < Date.parse(booking.scheduledStart) + booking.durationMinutes * 60_000); if (blackout) continue;
      const conflict = allBookings.some((item) => item.assignedProviderId === provider.userId && ["PROVIDER_ASSIGNED", "CONFIRMED"].includes(item.state) && overlaps(booking.scheduledStart, booking.durationMinutes, item.scheduledStart, item.durationMinutes)); if (conflict) continue;
      const reasons = ["approved provider", "eligible service", "service area match", "availability match"]; let score = 100; if (booking.requirements && provider.languages.some((language) => booking.requirements?.toLowerCase().includes(language.toLowerCase()))) { score += 5; reasons.push("language signal"); } candidates.push({ provider, score, reasons });
    }
    return candidates.sort((a, b) => b.score - a.score || a.provider.userId.localeCompare(b.provider.userId));
  }

  async startMatching(bookingId: string) { const booking = customerStore.transitionForMatching(bookingId); await providerRepository.expireRequests(); const candidates = await this.eligibleProviders(bookingId); const active = (await Promise.all((await providerRepository.listProviders()).map((provider) => providerRepository.listRequests(provider.userId)))).flat().filter((request) => request.bookingId === bookingId && ["CREATED", "SENT", "VIEWED"].includes(request.status)); const existing = new Set(active.map((request) => request.providerId)); const selected = candidates.filter((candidate) => !existing.has(candidate.provider.userId)).slice(0, Math.max(0, matchingConfig.maxActiveRequests - active.length)); const expiry = new Date(Date.now() + matchingConfig.requestExpiryMinutes * 60_000).toISOString(); const requests = []; for (const candidate of selected) requests.push(await providerRepository.createRequest(bookingId, candidate.provider.userId, candidate.score, candidate.reasons, expiry)); if (!active.length && !requests.length) customerStore.addEvent(booking, "NO_PROVIDER_AVAILABLE", "We could not find an available assistant for this time."); return { booking, candidates: candidates.length, requests }; }

  async listProviderRequests(providerId: string) { await providerRepository.expireRequests(); return providerRepository.listRequests(providerId); }
  async requestForProvider(providerId: string, requestId: string) { await providerRepository.expireRequests(); const request = await providerRepository.getRequest(providerId, requestId); const booking = customerStore.getBookingForSystem(request.bookingId); if (booking.customerId === providerId) throw new AppError("FORBIDDEN", "This request is not available.", 403); const address = customerStore.getAddressForSystem(booking.addressId); const { matchingScore: _score, scoreReasons: _reasons, ...safeRequest } = request; return { request: safeRequest, booking: { id: booking.id, reference: booking.reference, serviceName: booking.serviceName, scheduledStart: booking.scheduledStart, durationMinutes: booking.durationMinutes, requirements: booking.requirements, area: `${address.locality}, ${address.city}` } }; }
  async viewRequest(providerId: string, requestId: string) { const result = await this.requestForProvider(providerId, requestId); const transitioned = await providerRepository.transitionRequest(providerId, requestId, "VIEWED"); const { matchingScore: _score, scoreReasons: _reasons, ...request } = transitioned; return { ...result, request }; }
  async decline(providerId: string, requestId: string, reason: string) { const result = await this.requestForProvider(providerId, requestId); const transitioned = await providerRepository.transitionRequest(providerId, requestId, "DECLINED", reason); const { matchingScore: _score, scoreReasons: _reasons, ...request } = transitioned; await providerRepository.audit(providerId, providerId, "PROVIDER_REQUEST_DECLINED", reason); customerStore.addEvent(customerStore.getBookingForSystem(result.booking.id), "PROVIDER_DECLINED", "A provider declined this request.", false); return { ...result, request }; }
  async accept(providerId: string, requestId: string) { return this.withAssignmentLock(async () => { const result = await this.requestForProvider(providerId, requestId); const current = await providerRepository.getRequest(providerId, requestId); if (current.expiresAt && Date.parse(current.expiresAt) <= Date.now()) throw new AppError("REQUEST_EXPIRED", "This request is no longer available.", 409); const bookingRecord = customerStore.getBookingForSystem(result.booking.id); if (!(await providerRepository.isEligible(providerId, bookingRecord.serviceSlug))) throw new AppError("PROVIDER_NOT_ELIGIBLE", "You are no longer eligible for this service.", 403); const booking = customerStore.assignProvider(result.booking.id, providerId); const transitioned = await providerRepository.transitionRequest(providerId, requestId, "ACCEPTED"); const { matchingScore: _score, scoreReasons: _reasons, ...request } = transitioned; await providerRepository.cancelRequests(booking.id, requestId); await providerRepository.audit(providerId, providerId, "PROVIDER_REQUEST_ACCEPTED"); customerStore.addEvent(booking, "PROVIDER_ACCEPTED", "Your assistant has accepted the request.", false); return { request, booking }; }); }
  private withAssignmentLock<T>(operation: () => Promise<T>) { const next = assignmentQueue.then(operation, operation); assignmentQueue = next.then(() => undefined, () => undefined); return next; }
  async assignmentForCustomer(customerId: string, bookingId: string) { const booking = customerStore.getBooking(customerId, bookingId); if (!booking.assignedProviderId) return { status: booking.state === "SEARCHING_PROVIDER" ? "SEARCHING" : booking.state === "CANCELLED" ? "CANCELLED" : "RECEIVED", provider: undefined, booking }; return { status: "ASSIGNED", provider: await providerRepository.getPublicProfile(booking.assignedProviderId), booking }; }
  async adminMatching(bookingId: string) { const booking = customerStore.getBookingForSystem(bookingId); const requests = (await Promise.all((await providerRepository.listProviders()).map((provider) => providerRepository.listRequests(provider.userId)))).flat().filter((request) => request.bookingId === bookingId); return { booking, requests, candidateCount: requests.length }; }
  async manualAssign(actorId: string, bookingId: string, providerId: string) { return this.withAssignmentLock(async () => { const booking = customerStore.getBookingForSystem(bookingId); if (booking.state === "PENDING_PAYMENT") customerStore.transitionForMatching(bookingId); if (!(await providerRepository.isEligible(providerId, booking.serviceSlug))) throw new AppError("PROVIDER_NOT_ELIGIBLE", "Only approved eligible providers can be assigned.", 403); const assigned = customerStore.assignProvider(bookingId, providerId); await providerRepository.cancelRequests(bookingId); await providerRepository.audit(providerId, actorId, "MANUAL_PROVIDER_ASSIGNED", "Operations assignment"); return assigned; }); }
}

export const matchingService = new MatchingService();
