import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import test from "node:test";
import { buildServer } from "../src/server.js";
const customer = { "x-customer-id": "customer-phase6" };
async function createBooking(app: ReturnType<typeof buildServer>) { const address = await app.inject({ method: "POST", url: "/api/v1/customer/addresses", headers: customer, payload: { label: "Home", recipientName: "Ravi Rao", addressLine1: "12 Lake View Road", locality: "Indiranagar", city: "Bengaluru", state: "Karnataka", postalCode: "560038" } }); return app.inject({ method: "POST", url: "/api/v1/bookings", headers: customer, payload: { serviceSlug: "elder-companion", addressId: address.json().data.id, scheduledStart: "2099-05-04T10:00:00+05:30", durationMinutes: 120 } }); }
test("payment order is idempotent and server verification captures payment", async () => { const app = buildServer(); const booking = await createBooking(app); const headers = { ...customer, "idempotency-key": "payment-1" }; const first = await app.inject({ method: "POST", url: `/api/v1/bookings/${booking.json().data.id}/payment`, headers }); const second = await app.inject({ method: "POST", url: `/api/v1/bookings/${booking.json().data.id}/payment`, headers }); assert.equal(first.json().meta.paymentId, second.json().meta.paymentId); const order = first.json().data.orderId; const paymentId = "pay_test_1"; const signature = createHmac("sha256", "development-payment-secret").update(`${order}|${paymentId}`).digest("hex"); const verified = await app.inject({ method: "POST", url: `/api/v1/payments/${first.json().meta.paymentId}/verify`, headers: customer, payload: { paymentId, signature } }); assert.equal(verified.json().data.status, "CAPTURED"); const detail = await app.inject({ method: "GET", url: `/api/v1/bookings/${booking.json().data.id}`, headers: customer }); assert.equal(detail.json().data.state, "PAID"); await app.close(); });
test("invalid and duplicate webhooks are handled safely", async () => { const app = buildServer(); const booking = await createBooking(app); const order = await app.inject({ method: "POST", url: `/api/v1/bookings/${booking.json().data.id}/payment`, headers: { ...customer, "idempotency-key": "payment-hook" } }); const body = { paymentId: "pay_hook", orderId: order.json().data.orderId, status: "CAPTURED" as const }; const raw = JSON.stringify(body); const signature = createHmac("sha256", "development-payment-secret").update(raw).digest("hex"); const invalid = await app.inject({ method: "POST", url: "/api/v1/payments/webhook", headers: { "x-payment-signature": "bad", "x-payment-event-id": "hook-bad" }, payload: body }); assert.equal(invalid.statusCode, 400); const first = await app.inject({ method: "POST", url: "/api/v1/payments/webhook", headers: { "x-payment-signature": signature, "x-payment-event-id": "hook-1" }, payload: body }); const duplicate = await app.inject({ method: "POST", url: "/api/v1/payments/webhook", headers: { "x-payment-signature": signature, "x-payment-event-id": "hook-1" }, payload: body }); assert.equal(first.statusCode, 200); assert.equal(duplicate.json().data.duplicate, true); await app.close(); });
test("refund and admin financial access are protected", async () => { const app = buildServer(); const booking = await createBooking(app); const order = await app.inject({ method: "POST", url: `/api/v1/bookings/${booking.json().data.id}/payment`, headers: { ...customer, "idempotency-key": "payment-refund" } }); const paymentId = order.json().meta.paymentId; const signature = createHmac("sha256", "development-payment-secret").update(`${order.json().data.orderId}|pay_refund`).digest("hex"); await app.inject({ method: "POST", url: `/api/v1/payments/${paymentId}/verify`, headers: customer, payload: { paymentId: "pay_refund", signature } }); const refund = await app.inject({ method: "POST", url: `/api/v1/payments/${paymentId}/refund`, headers: customer, payload: { reason: "Customer changed plans" } }); assert.equal(refund.json().data.status, "COMPLETED"); const forbidden = await app.inject({ method: "GET", url: "/api/v1/admin/payments", headers: { "x-role": "CUSTOMER" } }); assert.equal(forbidden.statusCode, 403); await app.close(); });
