export const bookingStates = [
  "DRAFT", "PENDING_PAYMENT", "PAID", "SEARCHING_PROVIDER", "PROVIDER_ASSIGNED",
  "CONFIRMED", "PROVIDER_ON_THE_WAY", "ARRIVED", "SERVICE_STARTED", "SERVICE_PAUSED",
  "SERVICE_COMPLETED", "PAYMENT_SETTLED", "REVIEWED", "CANCELLED", "EXPIRED", "DISPUTED", "EMERGENCY"
] as const;
export type BookingState = (typeof bookingStates)[number];

const transitions: Record<BookingState, readonly BookingState[]> = {
  DRAFT: ["PENDING_PAYMENT", "CANCELLED"], PENDING_PAYMENT: ["PAID", "CANCELLED", "EXPIRED"],
  PAID: ["SEARCHING_PROVIDER", "CANCELLED"], SEARCHING_PROVIDER: ["PROVIDER_ASSIGNED", "CANCELLED", "EXPIRED"],
  PROVIDER_ASSIGNED: ["CONFIRMED", "CANCELLED"], CONFIRMED: ["PROVIDER_ON_THE_WAY", "CANCELLED", "EMERGENCY"],
  PROVIDER_ON_THE_WAY: ["ARRIVED", "CANCELLED", "EMERGENCY"], ARRIVED: ["SERVICE_STARTED", "EMERGENCY"],
  SERVICE_STARTED: ["SERVICE_PAUSED", "SERVICE_COMPLETED", "EMERGENCY"], SERVICE_PAUSED: ["SERVICE_STARTED", "SERVICE_COMPLETED", "EMERGENCY"],
  SERVICE_COMPLETED: ["PAYMENT_SETTLED", "DISPUTED"], PAYMENT_SETTLED: ["REVIEWED", "DISPUTED"],
  REVIEWED: [], CANCELLED: [], EXPIRED: [], DISPUTED: [], EMERGENCY: ["DISPUTED", "SERVICE_COMPLETED"]
};

export function canTransition(from: BookingState, to: BookingState): boolean {
  return transitions[from].includes(to);
}
