import { randomUUID } from "node:crypto";
import { AppError } from "../errors.js";
import { config } from "../config.js";
import { postgresPool } from "../db/postgres.js";
import type { AccountStatus, AvailabilityBlock, AvailabilityInput, AvailabilityPatch, EligibilityStatus, OnboardingStatus, ProviderAuditEvent, ProviderDocument, ProviderProfile, ProviderProfilePatch, ProviderRequest, ProviderRequestStatus, ProviderService, ProviderVerification, ServiceArea, VerificationStatus } from "./types.js";

export interface ProviderRepository {
  getProfile(providerId: string): Promise<ProviderProfile>;
  updateProfile(providerId: string, patch: ProviderProfilePatch): Promise<ProviderProfile>;
  listServices(providerId: string): Promise<ProviderService[]>;
  setServices(providerId: string, serviceSlugs: string[]): Promise<ProviderService[]>;
  listAvailability(providerId: string): Promise<AvailabilityBlock[]>;
  createAvailability(providerId: string, input: AvailabilityInput): Promise<AvailabilityBlock>;
  updateAvailability(providerId: string, id: string, input: AvailabilityPatch): Promise<AvailabilityBlock>;
  deleteAvailability(providerId: string, id: string): Promise<void>;
  getVerification(providerId: string): Promise<ProviderVerification[]>;
  listDocuments(providerId: string): Promise<ProviderDocument[]>;
  submitDocument(providerId: string, documentType: string, storageRef: string): Promise<ProviderDocument>;
  listProviders(): Promise<ProviderProfile[]>;
  getProviderForAdmin(providerId: string): Promise<ProviderProfile>;
  approve(providerId: string, actorId: string): Promise<ProviderProfile>;
  reject(providerId: string, actorId: string, reason: string): Promise<ProviderProfile>;
  suspend(providerId: string, actorId: string, reason: string): Promise<ProviderProfile>;
  submitForReview(providerId: string, actorId: string): Promise<ProviderProfile>;
  audit(providerId: string, actorId: string, action: string, reason?: string): Promise<ProviderAuditEvent>;
  getPublicProfile(providerId: string): Promise<Pick<ProviderProfile, "userId" | "displayName" | "profilePhotoRef" | "bio" | "languages" | "experienceSummary" | "serviceAreas"> & { services: ProviderService[]; verifications: Pick<ProviderVerification, "verificationType" | "status">[] }>;
  listRequests(providerId: string): Promise<ProviderRequest[]>;
  getRequest(providerId: string, requestId: string): Promise<ProviderRequest>;
  createRequest(bookingId: string, providerId: string, score?: number, reasons?: string[], expiresAt?: string): Promise<ProviderRequest>;
  transitionRequest(providerId: string, requestId: string, status: ProviderRequestStatus, declineReason?: string): Promise<ProviderRequest>;
  cancelRequests(bookingId: string, exceptRequestId?: string): Promise<void>;
  expireRequests(now?: string): Promise<ProviderRequest[]>;
  isEligible(providerId: string, serviceSlug: string): Promise<boolean>;
}

function profile(userId: string, status: OnboardingStatus, accountStatus: AccountStatus, displayName: string): ProviderProfile { return { userId, displayName, languages: ["English", "Hindi"], timezone: "Asia/Kolkata", onboardingStatus: status, accountStatus, serviceAreas: [] }; }

export class InMemoryProviderRepository implements ProviderRepository {
  private profiles = new Map<string, ProviderProfile>([
    ["provider-demo-incomplete", profile("provider-demo-incomplete", "PROFILE_INCOMPLETE", "ACTIVE", "Demo Provider · Profile incomplete")],
    ["provider-demo-approved", { ...profile("provider-demo-approved", "APPROVED", "ACTIVE", "Demo Provider · Approved"), bio: "Development-only approved profile. Not a real person.", experienceSummary: "Development demo profile", serviceAreas: [{ id: "area-demo", providerId: "provider-demo-approved", city: "Bengaluru", locality: "Indiranagar", radiusKm: 8 }] }],
    ["provider-demo-suspended", profile("provider-demo-suspended", "SUSPENDED", "SUSPENDED", "Demo Provider · Suspended")]
  ]);
  private services: ProviderService[] = [{ providerId: "provider-demo-approved", serviceSlug: "elder-companion", eligibilityStatus: "ELIGIBLE" }];
  private availability: AvailabilityBlock[] = [{ id: "availability-demo-approved", providerId: "provider-demo-approved", kind: "WEEKLY", dayOfWeek: 1, startTime: "00:00", endTime: "23:59", timezone: "Asia/Kolkata", active: true }];
  private documents: ProviderDocument[] = [];
  private verifications: ProviderVerification[] = [];
  private auditEvents: ProviderAuditEvent[] = [];
  private requests: ProviderRequest[] = [];
  async getProfile(providerId: string) { const item = this.profiles.get(providerId); if (!item) throw new AppError("NOT_FOUND", "Provider profile not found.", 404); return structuredClone(item); }
  async updateProfile(providerId: string, patch: ProviderProfilePatch) { const item = await this.getProfile(providerId); if (["APPROVED", "SUSPENDED", "DEACTIVATED"].includes(item.onboardingStatus)) { if (patch.displayName || patch.bio || patch.languages || patch.experienceSummary || patch.timezone) { /* approved providers may maintain their public profile */ } } Object.assign(item, patch); if (item.onboardingStatus === "REGISTERED") item.onboardingStatus = "PROFILE_INCOMPLETE"; if (item.displayName && item.bio && item.languages.length && item.experienceSummary) item.onboardingStatus = "PROFILE_COMPLETED"; this.profiles.set(providerId, item); return structuredClone(item); }
  async listServices(providerId: string) { return this.services.filter((item) => item.providerId === providerId).map((item) => structuredClone(item)); }
  async setServices(providerId: string, serviceSlugs: string[]) { this.services = this.services.filter((item) => item.providerId !== providerId); const result = serviceSlugs.map((serviceSlug) => ({ providerId, serviceSlug, eligibilityStatus: "PENDING" as EligibilityStatus })); this.services.push(...result); return structuredClone(result); }
  async listAvailability(providerId: string) { return this.availability.filter((item) => item.providerId === providerId).map((item) => structuredClone(item)); }
  async createAvailability(providerId: string, input: AvailabilityInput) { const list = await this.listAvailability(providerId); if (input.kind === "WEEKLY" && list.some((item) => item.kind === "WEEKLY" && item.dayOfWeek === input.dayOfWeek && item.startTime! < input.endTime! && input.startTime! < item.endTime!)) throw new AppError("AVAILABILITY_OVERLAP", "This availability overlaps an existing block.", 409); const item = { ...input, id: randomUUID(), providerId }; this.availability.push(item); return structuredClone(item); }
  async updateAvailability(providerId: string, id: string, input: AvailabilityPatch) { const item = this.availability.find((candidate) => candidate.id === id && candidate.providerId === providerId); if (!item) throw new AppError("NOT_FOUND", "Availability block not found.", 404); Object.assign(item, input); return structuredClone(item); }
  async deleteAvailability(providerId: string, id: string) { const index = this.availability.findIndex((item) => item.id === id && item.providerId === providerId); if (index < 0) throw new AppError("NOT_FOUND", "Availability block not found.", 404); this.availability.splice(index, 1); }
  async getVerification(providerId: string) { return this.verifications.filter((item) => item.providerId === providerId).map((item) => structuredClone(item)); }
  async listDocuments(providerId: string) { return this.documents.filter((item) => item.providerId === providerId).map((item) => structuredClone(item)); }
  async submitDocument(providerId: string, documentType: string, storageRef: string) { if (storageRef.startsWith("http://") || storageRef.startsWith("https://")) throw new AppError("INVALID_STORAGE_REF", "Documents must use a private storage reference.", 400); const item = { id: randomUUID(), providerId, documentType, storageRef, status: "PENDING" as VerificationStatus, uploadedAt: new Date().toISOString(), }; this.documents.push(item); await this.audit(providerId, providerId, "DOCUMENT_SUBMITTED"); return structuredClone(item); }
  async listProviders() { return [...this.profiles.values()].map((item) => structuredClone(item)); }
  async getProviderForAdmin(providerId: string) { return this.getProfile(providerId); }
  private async setStatus(providerId: string, actorId: string, status: OnboardingStatus, action: string, reason?: string) { const item = await this.getProfile(providerId); item.onboardingStatus = status; item.accountStatus = status === "SUSPENDED" ? "SUSPENDED" : status === "DEACTIVATED" ? "DEACTIVATED" : "ACTIVE"; this.profiles.set(providerId, item); await this.audit(providerId, actorId, action, reason); return item; }
  async approve(providerId: string, actorId: string) { const item = await this.getProfile(providerId); if (actorId === providerId) throw new AppError("FORBIDDEN", "Providers cannot approve themselves.", 403); if (item.accountStatus === "SUSPENDED") throw new AppError("PROVIDER_SUSPENDED", "A suspended provider cannot be approved without a separate reactivation workflow.", 409); return this.setStatus(providerId, actorId, "APPROVED", "PROVIDER_APPROVED"); }
  async reject(providerId: string, actorId: string, reason: string) { return this.setStatus(providerId, actorId, "REJECTED", "PROVIDER_REJECTED", reason); }
  async suspend(providerId: string, actorId: string, reason: string) { return this.setStatus(providerId, actorId, "SUSPENDED", "PROVIDER_SUSPENDED", reason); }
  async submitForReview(providerId: string, actorId: string) { const item = await this.getProfile(providerId); if (item.onboardingStatus !== "PROFILE_COMPLETED" && item.onboardingStatus !== "REJECTED") throw new AppError("INVALID_ONBOARDING_TRANSITION", "Complete the provider profile before submitting it for review.", 409); item.onboardingStatus = "VERIFICATION_PENDING"; this.profiles.set(providerId, item); await this.audit(providerId, actorId, "VERIFICATION_SUBMITTED"); return item; }
  async audit(providerId: string, actorId: string, action: string, reason?: string) { const item = { id: randomUUID(), providerId, actorId, action, reason, createdAt: new Date().toISOString() }; this.auditEvents.push(item); return structuredClone(item); }
  async getPublicProfile(providerId: string) { const item = await this.getProfile(providerId); return { userId: item.userId, displayName: item.displayName, profilePhotoRef: item.profilePhotoRef, bio: item.bio, languages: item.languages, experienceSummary: item.experienceSummary, serviceAreas: item.serviceAreas, services: await this.listServices(providerId), verifications: (await this.getVerification(providerId)).map(({ verificationType, status }) => ({ verificationType, status })) }; }
  async listRequests(providerId: string) { return this.requests.filter((item) => item.providerId === providerId).map((item) => structuredClone(item)); }
  async getRequest(providerId: string, requestId: string) { const item = this.requests.find((candidate) => candidate.id === requestId && candidate.providerId === providerId); if (!item) throw new AppError("NOT_FOUND", "Provider request not found.", 404); return structuredClone(item); }
  async createRequest(bookingId: string, providerId: string, score = 0, reasons: string[] = [], expiresAt = new Date(Date.now() + 600_000).toISOString()) { const duplicate = this.requests.find((item) => item.bookingId === bookingId && item.providerId === providerId && !["DECLINED", "EXPIRED", "CANCELLED"].includes(item.status)); if (duplicate) return structuredClone(duplicate); const now = new Date().toISOString(); const item: ProviderRequest = { id: randomUUID(), bookingId, providerId, status: "SENT", sentAt: now, expiresAt, matchingScore: score, scoreReasons: reasons, createdAt: now, updatedAt: now }; this.requests.push(item); return structuredClone(item); }
  async transitionRequest(providerId: string, requestId: string, status: ProviderRequestStatus, declineReason?: string) { const item = this.requests.find((candidate) => candidate.id === requestId && candidate.providerId === providerId); if (!item) throw new AppError("NOT_FOUND", "Provider request not found.", 404); if (item.expiresAt && Date.parse(item.expiresAt) <= Date.now() && !["EXPIRED", "CANCELLED"].includes(item.status)) item.status = "EXPIRED"; const allowed: Record<ProviderRequestStatus, ProviderRequestStatus[]> = { CREATED: ["SENT", "CANCELLED", "EXPIRED"], SENT: ["VIEWED", "ACCEPTED", "DECLINED", "CANCELLED", "EXPIRED"], VIEWED: ["ACCEPTED", "DECLINED", "CANCELLED", "EXPIRED"], ACCEPTED: [], DECLINED: [], EXPIRED: [], CANCELLED: [] }; if (!allowed[item.status].includes(status)) throw new AppError("INVALID_REQUEST_TRANSITION", "This provider request is no longer actionable.", 409); const now = new Date().toISOString(); item.status = status; item.updatedAt = now; if (status === "VIEWED") item.viewedAt = now; if (["ACCEPTED", "DECLINED"].includes(status)) item.respondedAt = now; if (declineReason) item.declineReason = declineReason; return structuredClone(item); }
  async cancelRequests(bookingId: string, exceptRequestId?: string) { for (const item of this.requests) if (item.bookingId === bookingId && item.id !== exceptRequestId && ["CREATED", "SENT", "VIEWED"].includes(item.status)) { item.status = "CANCELLED"; item.updatedAt = new Date().toISOString(); } }
  async expireRequests(now = new Date().toISOString()) { const expired: ProviderRequest[] = []; for (const item of this.requests) if (item.expiresAt && Date.parse(item.expiresAt) <= Date.parse(now) && ["CREATED", "SENT", "VIEWED"].includes(item.status)) { item.status = "EXPIRED"; item.updatedAt = now; expired.push(structuredClone(item)); } return expired; }
  async isEligible(providerId: string, serviceSlug: string) { const item = await this.getProfile(providerId); return item.onboardingStatus === "APPROVED" && item.accountStatus === "ACTIVE" && (await this.listServices(providerId)).some((service) => service.serviceSlug === serviceSlug && service.eligibilityStatus === "ELIGIBLE"); }
}

export type SqlExecutor = { query<T = unknown>(text: string, values?: readonly unknown[]): Promise<{ rows: T[] }> };
export class PostgresProviderRepository {
  constructor(private readonly db: SqlExecutor) {}
  async getProfile(providerId: string) { const result = await this.db.query<ProviderProfile>("SELECT user_id AS \"userId\", display_name AS \"displayName\", profile_photo_ref AS \"profilePhotoRef\", bio, gender, languages, experience_summary AS \"experienceSummary\", timezone, onboarding_status AS \"onboardingStatus\", account_status AS \"accountStatus\" FROM provider_profiles WHERE user_id = $1", [providerId]); if (!result.rows[0]) throw new AppError("NOT_FOUND", "Provider profile not found.", 404); return { ...result.rows[0], serviceAreas: [] }; }
  async updateProfile(providerId: string, patch: ProviderProfilePatch) { const current = await this.getProfile(providerId); const next = { ...current, displayName: patch.displayName ?? current.displayName, profilePhotoRef: patch.profilePhotoRef ?? current.profilePhotoRef, bio: patch.bio ?? current.bio, gender: patch.gender ?? current.gender, languages: patch.languages ?? current.languages, experienceSummary: patch.experienceSummary ?? current.experienceSummary, timezone: patch.timezone ?? current.timezone }; await this.db.query("UPDATE provider_profiles SET display_name = $2, profile_photo_ref = $3, bio = $4, gender = $5, languages = $6, experience_summary = $7, timezone = $8, updated_at = now() WHERE user_id = $1", [providerId, next.displayName, next.profilePhotoRef ?? null, next.bio ?? null, next.gender ?? null, next.languages, next.experienceSummary ?? null, next.timezone]); return next; }
  async listServices(providerId: string) { const result = await this.db.query<ProviderService>("SELECT provider_id AS \"providerId\", service_slug AS \"serviceSlug\", eligibility_status AS \"eligibilityStatus\" FROM provider_services WHERE provider_id = $1", [providerId]); return result.rows; }
  async setServices(providerId: string, serviceSlugs: string[]) { await this.db.query("DELETE FROM provider_services WHERE provider_id = $1", [providerId]); for (const slug of serviceSlugs) await this.db.query("INSERT INTO provider_services (provider_id, service_slug) VALUES ($1, $2)", [providerId, slug]); return this.listServices(providerId); }
  async listAvailability(providerId: string) { const result = await this.db.query<AvailabilityBlock>("SELECT id, provider_id AS \"providerId\", kind, day_of_week AS \"dayOfWeek\", start_time AS \"startTime\", end_time AS \"endTime\", timezone, starts_at AS \"startsAt\", ends_at AS \"endsAt\", active FROM provider_availability WHERE provider_id = $1 ORDER BY created_at", [providerId]); return result.rows; }
  async createAvailability(providerId: string, input: AvailabilityInput) { const result = await this.db.query<AvailabilityBlock>("INSERT INTO provider_availability (provider_id, kind, day_of_week, start_time, end_time, timezone, starts_at, ends_at, active) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id, provider_id AS \"providerId\", kind, day_of_week AS \"dayOfWeek\", start_time AS \"startTime\", end_time AS \"endTime\", timezone, starts_at AS \"startsAt\", ends_at AS \"endsAt\", active", [providerId, input.kind, input.dayOfWeek ?? null, input.startTime ?? null, input.endTime ?? null, input.timezone, input.startsAt ?? null, input.endsAt ?? null, input.active]); if (!result.rows[0]) throw new AppError("DATABASE_ERROR", "The provider availability could not be saved.", 500); return result.rows[0]; }
  async updateAvailability(providerId: string, id: string, input: AvailabilityPatch) { const result = await this.db.query<AvailabilityBlock>("UPDATE provider_availability SET kind = COALESCE($3, kind), day_of_week = COALESCE($4, day_of_week), start_time = COALESCE($5, start_time), end_time = COALESCE($6, end_time), timezone = COALESCE($7, timezone), starts_at = COALESCE($8, starts_at), ends_at = COALESCE($9, ends_at), active = COALESCE($10, active) WHERE id = $1 AND provider_id = $2 RETURNING id, provider_id AS \"providerId\", kind, day_of_week AS \"dayOfWeek\", start_time AS \"startTime\", end_time AS \"endTime\", timezone, starts_at AS \"startsAt\", ends_at AS \"endsAt\", active", [id, providerId, input.kind ?? null, input.dayOfWeek ?? null, input.startTime ?? null, input.endTime ?? null, input.timezone ?? null, input.startsAt ?? null, input.endsAt ?? null, input.active ?? null]); if (!result.rows[0]) throw new AppError("NOT_FOUND", "Availability block not found.", 404); return result.rows[0]; }
  async deleteAvailability(providerId: string, id: string) { const result = await this.db.query("DELETE FROM provider_availability WHERE id = $1 AND provider_id = $2", [id, providerId]); if (!result) throw new AppError("DATABASE_ERROR", "Availability could not be deleted.", 500); }
  async getVerification(providerId: string) { const result = await this.db.query<ProviderVerification>("SELECT id, provider_id AS \"providerId\", verification_type AS \"verificationType\", status, external_reference AS \"externalReference\", submitted_at AS \"submittedAt\", completed_at AS \"completedAt\", expires_at AS \"expiresAt\", true AS \"developmentOnly\" FROM provider_verifications WHERE provider_id = $1", [providerId]); return result.rows; }
  async listDocuments(providerId: string) { const result = await this.db.query<ProviderDocument>("SELECT id, provider_id AS \"providerId\", document_type AS \"documentType\", status, storage_ref AS \"storageRef\", uploaded_at AS \"uploadedAt\", reviewed_at AS \"reviewedAt\", rejection_reason AS \"rejectionReason\" FROM provider_documents WHERE provider_id = $1", [providerId]); return result.rows; }
  async submitDocument(providerId: string, documentType: string, storageRef: string) { const result = await this.db.query<ProviderDocument>("INSERT INTO provider_documents (provider_id, document_type, storage_ref) VALUES ($1,$2,$3) RETURNING id, provider_id AS \"providerId\", document_type AS \"documentType\", status, storage_ref AS \"storageRef\", uploaded_at AS \"uploadedAt\"", [providerId, documentType, storageRef]); if (!result.rows[0]) throw new AppError("DATABASE_ERROR", "The document metadata could not be saved.", 500); return result.rows[0]; }
  async listProviders() { const result = await this.db.query<ProviderProfile>("SELECT user_id AS \"userId\", display_name AS \"displayName\", profile_photo_ref AS \"profilePhotoRef\", bio, languages, experience_summary AS \"experienceSummary\", timezone, onboarding_status AS \"onboardingStatus\", account_status AS \"accountStatus\" FROM provider_profiles ORDER BY updated_at DESC"); const profiles: ProviderProfile[] = []; for (const item of result.rows) { const areas = await this.db.query<ServiceArea>("SELECT id, provider_id AS \"providerId\", city, locality, radius_km AS \"radiusKm\" FROM provider_service_areas WHERE provider_id = $1", [item.userId]); profiles.push({ ...item, serviceAreas: areas.rows }); } return profiles; }
  async getProviderForAdmin(providerId: string) { return this.getProfile(providerId); }
  async approve(providerId: string, actorId: string) { if (providerId === actorId) throw new AppError("FORBIDDEN", "Providers cannot approve themselves.", 403); const current = await this.getProfile(providerId); if (current.accountStatus === "SUSPENDED") throw new AppError("PROVIDER_SUSPENDED", "A suspended provider cannot be approved without a separate reactivation workflow.", 409); await this.db.query("UPDATE provider_profiles SET onboarding_status = 'APPROVED', account_status = 'ACTIVE', updated_at = now() WHERE user_id = $1 AND account_status <> 'SUSPENDED'", [providerId]); return this.getProfile(providerId); }
  async reject(providerId: string, _actorId: string, _reason: string) { await this.db.query("UPDATE provider_profiles SET onboarding_status = 'REJECTED', updated_at = now() WHERE user_id = $1", [providerId]); return this.getProfile(providerId); }
  async suspend(providerId: string, _actorId: string, _reason: string) { await this.db.query("UPDATE provider_profiles SET onboarding_status = 'SUSPENDED', account_status = 'SUSPENDED', updated_at = now() WHERE user_id = $1", [providerId]); return this.getProfile(providerId); }
  async submitForReview(providerId: string, actorId: string) { await this.db.query("UPDATE provider_profiles SET onboarding_status = 'VERIFICATION_PENDING', updated_at = now() WHERE user_id = $1 AND onboarding_status IN ('PROFILE_COMPLETED','REJECTED')", [providerId]); await this.audit(providerId, actorId, "VERIFICATION_SUBMITTED"); return this.getProfile(providerId); }
  async audit(providerId: string, actorId: string, action: string, reason?: string) { const result = await this.db.query<ProviderAuditEvent>("INSERT INTO provider_audit_events (provider_id, actor_id, action, reason) VALUES ($1,$2,$3,$4) RETURNING id, provider_id AS \"providerId\", actor_id AS \"actorId\", action, reason, created_at AS \"createdAt\"", [providerId, actorId, action, reason ?? null]); if (!result.rows[0]) throw new AppError("DATABASE_ERROR", "The audit event could not be saved.", 500); return result.rows[0]; }
  async getPublicProfile(providerId: string) { const item = await this.getProfile(providerId); return { ...item, services: await this.listServices(providerId), verifications: (await this.getVerification(providerId)).map(({ verificationType, status }) => ({ verificationType, status })) }; }
  async listRequests(providerId: string) { const result = await this.db.query<ProviderRequest>("SELECT id, booking_id AS \"bookingId\", provider_id AS \"providerId\", status, sent_at AS \"sentAt\", viewed_at AS \"viewedAt\", responded_at AS \"respondedAt\", expires_at AS \"expiresAt\", decline_reason AS \"declineReason\", matching_score AS \"matchingScore\", score_reasons AS \"scoreReasons\", created_at AS \"createdAt\", updated_at AS \"updatedAt\" FROM provider_requests WHERE provider_id = $1 ORDER BY created_at DESC", [providerId]); return result.rows; }
  async getRequest(providerId: string, requestId: string) { const result = await this.db.query<ProviderRequest>("SELECT id, booking_id AS \"bookingId\", provider_id AS \"providerId\", status, sent_at AS \"sentAt\", viewed_at AS \"viewedAt\", responded_at AS \"respondedAt\", expires_at AS \"expiresAt\", decline_reason AS \"declineReason\", matching_score AS \"matchingScore\", score_reasons AS \"scoreReasons\", created_at AS \"createdAt\", updated_at AS \"updatedAt\" FROM provider_requests WHERE provider_id = $1 AND id = $2", [providerId, requestId]); if (!result.rows[0]) throw new AppError("NOT_FOUND", "Provider request not found.", 404); return result.rows[0]; }
  async createRequest(bookingId: string, providerId: string, score = 0, reasons: string[] = [], expiresAt = new Date(Date.now() + 600_000).toISOString()) { const result = await this.db.query<ProviderRequest>("INSERT INTO provider_requests (booking_id, provider_id, status, sent_at, expires_at, matching_score, score_reasons) VALUES ($1,$2,'SENT',now(),$3,$4,$5) ON CONFLICT (booking_id, provider_id) DO UPDATE SET updated_at = now() RETURNING id, booking_id AS \"bookingId\", provider_id AS \"providerId\", status, sent_at AS \"sentAt\", expires_at AS \"expiresAt\", matching_score AS \"matchingScore\", score_reasons AS \"scoreReasons\", created_at AS \"createdAt\", updated_at AS \"updatedAt\"", [bookingId, providerId, expiresAt, score, reasons]); if (!result.rows[0]) throw new AppError("DATABASE_ERROR", "The provider request could not be saved.", 500); return result.rows[0]; }
  async transitionRequest(providerId: string, requestId: string, status: ProviderRequestStatus, declineReason?: string) { const result = await this.db.query<ProviderRequest>("UPDATE provider_requests SET status = $3, viewed_at = CASE WHEN $3 = 'VIEWED' THEN now() ELSE viewed_at END, responded_at = CASE WHEN $3 IN ('ACCEPTED','DECLINED') THEN now() ELSE responded_at END, decline_reason = COALESCE($4, decline_reason), updated_at = now() WHERE provider_id = $1 AND id = $2 AND status IN ('CREATED','SENT','VIEWED') AND (expires_at IS NULL OR expires_at > now()) RETURNING id, booking_id AS \"bookingId\", provider_id AS \"providerId\", status, sent_at AS \"sentAt\", viewed_at AS \"viewedAt\", responded_at AS \"respondedAt\", expires_at AS \"expiresAt\", decline_reason AS \"declineReason\", matching_score AS \"matchingScore\", score_reasons AS \"scoreReasons\", created_at AS \"createdAt\", updated_at AS \"updatedAt\"", [providerId, requestId, status, declineReason ?? null]); if (!result.rows[0]) throw new AppError("INVALID_REQUEST_TRANSITION", "This provider request is no longer actionable.", 409); return result.rows[0]; }
  async cancelRequests(bookingId: string, exceptRequestId?: string) { await this.db.query("UPDATE provider_requests SET status = 'CANCELLED', updated_at = now() WHERE booking_id = $1 AND status IN ('CREATED','SENT','VIEWED') AND ($2 IS NULL OR id <> $2)", [bookingId, exceptRequestId ?? null]); }
  async expireRequests() { const result = await this.db.query<ProviderRequest>("UPDATE provider_requests SET status = 'EXPIRED', updated_at = now() WHERE status IN ('CREATED','SENT','VIEWED') AND expires_at <= now() RETURNING id, booking_id AS \"bookingId\", provider_id AS \"providerId\", status, created_at AS \"createdAt\", updated_at AS \"updatedAt\""); return result.rows; }
  async isEligible(providerId: string, serviceSlug: string) { const profile = await this.getProfile(providerId); return profile.onboardingStatus === "APPROVED" && profile.accountStatus === "ACTIVE" && (await this.listServices(providerId)).some((item) => item.serviceSlug === serviceSlug && item.eligibilityStatus === "ELIGIBLE"); }
}

export function createProviderRepository(options: { mode: "memory" | "postgres"; client?: SqlExecutor }): ProviderRepository {
  if (options.mode === "postgres") { if (!options.client) throw new AppError("DATABASE_NOT_CONFIGURED", "PostgreSQL provider repository requires a SQL client.", 503); return new PostgresProviderRepository(options.client); }
  return new InMemoryProviderRepository();
}

// Runtime wiring remains explicitly development-memory until the application database client is configured.
export const providerRepository = createProviderRepository({
  mode: config.PERSISTENCE_MODE,
  ...(postgresPool ? { client: postgresPool } : {})
});
